name = "lightms"
# main = "src/worker/index.ts"
compatibility_date = "2026-09-01"

pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "lightms-d1-prod"
database_id = "407039a4-d2ca-4c8c-8ba4-45b8a3697828"
